twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/Shared/Presentation/templates': 'shared'
        '%kernel.project_dir%/src/Quran/Presentation/templates': 'quran'
        '%kernel.project_dir%/src/Context/Presentation/Template': 'context'

when@test:
    twig:
        strict_variables: true
