version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432'
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data:rw
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000'
    volumes:
      - ./:/var/www/symfony
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80'
      - '443'
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    environment:
      - NGINX_HOST=dev.iqra.docker
    depends_on:
      - php
      - postgres
      - certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  node:
    container_name: node
    image: node:16.16-alpine
    working_dir: /var/www/symfony
    volumes:
      - ./:/var/www/symfony
    ports:
      - "8080"
    tty: true
