version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432'
    volumes:
      - ${PWD}/docker/postgres/data:/var/lib/postgresql/data:rw
  php:
    container_name: php
    build:
      context: ${PWD}/docker/php
    ports:
      - '9000'
    volumes:
      - ${PWD}:/var/www/symfony
      - ${PWD}/docker/php/php.ini:/usr/local/etc/php/php.ini:ro
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80'
    volumes:
      - ${PWD}:/var/www/symfony
      - ${PWD}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
      - ${PWD}/docker/logs/nginx/:/var/log/nginx:delegated
    depends_on:
      - php
      - postgres
  node:
    container_name: node
    image: node:16.16-alpine
    working_dir: /var/www/symfony
    volumes:
      - ${PWD}:/var/www/symfony
    ports:
      - "8080"
    tty: true
