version: '3.8'

services:
  database:
    image: 'postgres:14.5'
    environment:
      POSTGRES_PASSWORD: iqra
      POSTGRES_USER: iqra
      POSTGRES_DB: iqra
    ports:
      - '5432'
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data:rw
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000'
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80'
    volumes:
      - ./:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
