name: Iqra
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: github_actions_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_PASSWORD:
        ports:
          - "3306:3306"
    steps:
      - name: Setup Php and Composer
        uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.0'
      - name: Check PHP Version
        run: php -v
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Copy .env.local
        run: php -r "file_exists('.env.local') || copy('.env', '.env.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run:  |
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name:  Install Symfony CLI
        run: |
          wget https://get.symfony.com/cli/installer -O - | bash
          mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
      - name: Check Symfony Requirements
        run: symfony check:requirements
      - name: PHP CS Fixer - Coding Standards Checks
        run: make lint-cs
      - name: Psalm - Static Analysis Of PHP Code
        run: make lint-ps
      - name: Twig - Linting Twig Templates
        run: make lint-twig
